### ISSUE TITLE
Restricts OS to a size of 127GB.   

### ISSUE THREAD

**Issue by runxc1** [azure-contrib/WindowsAzureDiskResizer#4]
Azure has recently octupled the size of the disk for os disks.

**Comment by maartenba** [comment]
That should be an easy change. Feel free to do a PR, currently not able to do this (mobile)

**Comment by zenzei** [comment]
Great Maarten thanks for the tool. it works great! By the way, is the WindowsAzureDiskResizer
binaries with this fix available online so I can avoid compiling? I don't have Visual Studio on my environment. Thanks in advance!

**Comment by maartenba** [comment]
Cool!
